In [1]:
import numpy as np
import pandas as pd

## Data retribval and mapping of category

In [2]:
data = pd.read_csv('./data_with_sub_categories.csv')
data.head()

,scheme_name,Scheme Codes,expense_ratio,risk_level,returns_1yr,returns_3yr,returns_5yr,Sub_Category
0,Aditya Birla SL Active Debt Multi-Mgr FoF-Dir ...,100033,0.27,0.2,4.0,6.5,6.9,FoFs Domestic
1,Aditya Birla SL Arbitrage Fund,100034,0.36,0.0,5.6,4.8,5.5,Arbitrage Mutual Funds
2,Aditya Birla SL Asset Allocator FoF-Dir Growth,100037,0.53,0.4,2.0,18.9,9.7,FoFs Domestic
3,Aditya Birla SL Balanced Advantage Fund,100038,0.61,0.5,4.5,18.6,9.7,Dynamic Asset Allocation or Balanced Advantage
4,Aditya Birla SL Banking&Financial Services-Dir...,100041,1.17,0.5,5.3,24.6,9.2,Sectoral / Thematic Mutual Funds

In [3]:
scheme_code_to_names=dict(zip(data['Scheme Codes'], data['scheme_name']))
scheme_code_to_risk=dict(zip(data['Scheme Codes'], data['risk_level']))

In [4]:
scheme_code_to_names

{100033: 'Aditya Birla SL Active Debt Multi-Mgr FoF-Dir Growth',
 100034: 'Aditya Birla SL Arbitrage Fund',
 100037: 'Aditya Birla SL Asset Allocator FoF-Dir Growth',
 100038: 'Aditya Birla SL Balanced Advantage Fund',
 100041: 'Aditya Birla SL Banking&Financial Services-DirGrowth',
 100042: 'Aditya Birla SL Banking&PSU Debt Fund',
 100043: 'Aditya Birla SL Corporate Bond Fund',
 100044: 'Aditya Birla SL Credit Risk Fund',
 100046: 'Aditya Birla SL Digital India Fund',
 100047: 'Aditya Birla SL Dividend Yield Fund',
 100048: 'Aditya Birla SL Dynamic Bond Fund',
 100049: 'Aditya Birla SL Equity Advantage Fund',
 100051: 'Aditya Birla SL Equity Hybrid ’95 Fund',
 100052: 'Aditya Birla SL Equity Savings Fund',
 100053: 'Aditya Birla SL Flexi Cap Fund',
 100054: 'Aditya Birla SL Floating Rate Fund',
 100055: 'Aditya Birla SL Focused Equity Fund',
 100056: 'Aditya Birla SL FP FoF – Aggressive – Direct Growth',
 100057: 'Aditya Birla SL FP FoF – Conservative – Direct Growth',
 100058: 'Aditya Birla SL FP FoF – Moderate – Direct Growth',
 100059: 'Aditya Birla SL Frontline Equity Fund',
 100060: 'Aditya Birla SL Gold Fund',
 100061: 'Aditya Birla SL Govt Securities Fund',
 100062: 'Aditya Birla SL Income Fund',
 100063: 'Aditya Birla SL India GenNext Fund',
 100064: 'Aditya Birla SL Infrastructure Fund',
 100065: 'Aditya Birla SL Inter Equity – Plan B-Direct Growth',
 100066: 'Aditya Birla SL Liquid Fund',
 100067: 'Aditya Birla SL Low Duration Fund',
 100956: 'Aditya Birla SL Manufacturing Equity Fund',
 100970: 'Aditya Birla SL Medium Term Plan – Direct Growth',
 100971: 'Aditya Birla SL Midcap Fund',
 100972: 'Aditya Birla SL Money Manager Fund',
 101313: 'Aditya Birla SL Nifty 50 Index Fund',
 101314: 'Aditya Birla SL Pure Value Fund',
 101315: 'Aditya Birla SL Regular Savings Fund',
 101316: 'Aditya Birla SL Savings Fund',
 101317: 'Aditya Birla SL Short Term Fund',
 101318: 'Aditya Birla SL Small Cap Fund',
 101591: 'Aditya Birla SL Tax Relief ’96 – Direct Growth',
 112210: 'AXIS Arbitrage Fund',
 112211: 'AXIS Balanced Advantage Fund',
 112212: 'AXIS Banking & PSU Debt Fund',
 112213: 'AXIS Bluechip Fund',
 112214: 'AXIS Children’s Gift Fund',
 112215: 'AXIS Corporate Debt Fund',
 112216: 'AXIS Credit Risk Fund',
 112217: 'AXIS Dynamic Bond Fund',
 112277: 'AXIS Equity Saver Fund',
 112278: 'AXIS Flexi Cap Fund',
 112322: 'AXIS Focused 25 Fund',
 112323: 'AXIS Gilt Fund',
 112354: 'AXIS Gold Fund',
 112355: 'AXIS Liquid Fund',
 112369: 'AXIS Long Term Equity Fund',
 112679: 'AXIS Midcap Fund',
 112680: 'AXIS Regular Saver Fund',
 112681: 'AXIS Short Term Fund',
 112682: 'AXIS Small Cap Fund',
 112683: 'AXIS Strategic Bond Fund',
 112684: 'AXIS Treasury Advantage Fund',
 112712: 'AXIS Triple Advantage Fund',
 118484: 'Bandhan Asset Allocation FoF – Moderate – Direct Growth',
 109255: 'Bank of India Balanced Advantage Fund',
 109264: 'Bank of India Conservative Hybrid Fund',
 109269: 'Bank of India Credit Risk Fund',
 110606: 'Bank of India Large & Mid Cap Equity Fund',
 110607: 'Bank of India Liquid Fund',
 110608: 'Bank of India Manufacturing & Infrastr Fund',
 111585: 'Bank of India Mid & Small Cap Equity & Debt Fund',
 111589: 'Bank of India Midcap Tax Fund',
 111590: 'Bank of India Short Term Income – Direct Growth',
 111709: 'Bank of India Tax Advantage Fund',
 111710: 'Bank of India Ultra Short Duration Fund',
 113036: 'Baroda BNP Paribas Aggressive Hybrid Fund',
 119333: 'Baroda BNP Paribas Arbitrage Fund',
 119334: 'Baroda BNP Paribas Banking&Fin Serv Fund',
 119340: 'Baroda BNP Paribas Conservative Hybrid Fund',
 119354: 'Baroda BNP Paribas Corporate Bond Fund',
 119399: 'Baroda BNP Paribas Credit Risk Fund',
 119400: 'Baroda BNP Paribas Dynamic Bond Fund',
 119415: 'Baroda BNP Paribas ELSS Fund',
 119416: 'Baroda BNP Paribas Focused Fund',
 133488: 'Baroda BNP Paribas Gilt Fund',
 133517: 'Baroda BNP Paribas Large Cap Fund',
 133518: 'Baroda BNP Paribas Liquid Fund',
 133520: 'Baroda BNP Paribas Low Duration Fund',
 139344: 'Baroda BNP Paribas Medium Duration Fund',
 140463: 'Baroda BNP Paribas Mid Cap Fund',
 142245: 'Baroda BNP Paribas Multi Cap Fund',
 142246: 'Baroda BNP Paribas Short Duration Fund',
 100589: 'Canara Robeco Bluechip Equity Fund',
 100590: 'Canara Robeco Conservative Hybrid Fund',
 100593: 'Canara Robeco Consumer Trends Fund',
 100596: 'Canara Robeco Corporate Bond Fund',
 100597: 'Canara Robeco Dynamic Bond Fund',
 100600: 'Canara Robeco Emerging Equities – Direct Growth',
 100601: 'Canara Robeco Equity Hybrid Fund',
 101361: 'Canara Robeco Equity Tax Saver Fund',
 101362: 'Canara Robeco Flexi Cap Fund',
 101363: 'Canara Robeco Gilt Fund',
 101364: 'Canara Robeco Income Fund',
 101365: 'Canara Robeco Infrastructure – Direct Growth',
 101587: 'Canara Robeco Liquid Fund',
 101588: 'Canara Robeco Savings Fund',
 101589: 'Canara Robeco Short Duration Fund',
 101922: 'Canara Robeco Ultra Short Term Fund',
 100077: 'DSP Arbitrage Fund',
 100078: 'DSP Banking & Psu Debt Fund',
 100079: 'DSP Bond Fund',
 100080: 'DSP Credit Risk Fund',
 100081: 'DSP Dynamic Asset Allocation Fund',
 100082: 'DSP Equity & Bond Fund',
 100084: 'DSP Equity Opportunities Fund',
 100085: 'DSP Equity Savings Fund',
 100086: 'DSP Flexi Cap Fund',
 100087: 'DSP Focus Fund',
 100088: 'DSP G-Sec Fund',
 100089: 'DSP India T.I.G.E.R. Fund',
 100090: 'DSP Liquidity Fund',
 100940: 'DSP Low Duration Fund',
 100941: 'DSP Midcap Fund',
 100943: 'DSP Natural Resources & New Energy – Direct Growth',
 101303: 'DSP Nifty 50 Equal Weight Index Fund',
 101304: 'DSP Regular Savings Fund',
 101305: 'DSP Savings Fund',
 101306: 'DSP Short Term Fund',
 101635: 'DSP Small Cap Fund',
 101636: 'DSP Strategic Bond Fund',
 101742: 'DSP Tax Saver Fund',
 101743: 'DSP Top 100 Equity Fund',
 101744: 'DSP Ultra Short Fund',
 109934: 'Edelweiss Aggressive Hybrid Fund',
 109935: 'Edelweiss Arbitrage Fund',
 109936: 'Edelweiss Balanced Advantage Fund',
 109937: 'Edelweiss Banking & Psu Debt Fund',
 109938: 'Edelweiss Equity Savings Fund',
 109939: 'Edelweiss Flexi Cap Fund',
 109940: 'Edelweiss Govt Securities Fund',
 109941: 'Edelweiss Large & Mid Cap Fund',
 109942: 'Edelweiss Large Cap Fund',
 109944: 'Edelweiss Liquid Fund',
 109945: 'Edelweiss Long Term Equity Fund',
 109946: 'Edelweiss Mid Cap Fund',
 109949: 'Edelweiss Money Market Fund',
 109950: 'Edelweiss Recently Listed IPO Fund',
 100470: 'Franklin Build India Fund',
 100471: 'Franklin India Banking & PSU Debt Fund',
 100472: 'Franklin India Bluechip Fund',
 100473: 'Franklin India Corporate Debt Fund',
 100481: 'Franklin India Debt Hybrid Fund',
 100482: 'Franklin India Dynamic Asset Allocation FoFs-Dir-G',
 100483: 'Franklin India Equity Advantage Fund',
 100484: 'Franklin India Equity Hybrid Fund',
 100485: 'Franklin India Flexi Cap Fund',
 100486: 'Franklin India Floating Rate Fund',
 100487: 'Franklin India Focused Equity Fund',
 100489: 'Franklin India G-Sec Fund',
 100490: 'Franklin India Liquid Fund',
 100491: 'Franklin India Multi-Asset Solution Fund',
 100493: 'Franklin India NSE Nifty 50 Index Fund',
 100494: 'Franklin India Opportunities Fund',
 100495: 'Franklin India Prima Fund',
 100498: 'Franklin India Savings Fund',
 100499: 'Franklin India Smaller Companies Fund',
 100503: 'Franklin India Taxshield – Direct Growth',
 100504: 'Franklin India Technology Fund',
 100119: 'HDFC Arbitrage Fund',
 100120: 'HDFC Balanced Advantage Fund',
 100121: 'HDFC Banking and PSU Debt Fund',
 100122: 'HDFC Capital Builder Value Fund',
 100123: 'HDFC Children’s Gift Fund',
 100124: 'HDFC Corporate Bond Fund',
 100282: 'HDFC Credit Risk Debt Fund',
 100283: 'HDFC Dynamic Debt Fund',
 100284: 'HDFC Dynamic PE Ratio Fund',
 100285: 'HDFC Equity Savings Fund',
 100868: 'HDFC Flexi Cap Fund',
 100869: 'HDFC Floating Rate Debt Fund',
 100870: 'HDFC Focused 30 Fund',
 100871: 'HDFC Gilt Fund',
 100872: 'HDFC Gold Fund',
 100873: 'HDFC Housing Opportunities Fund',
 100874: 'HDFC Hybrid Debt Fund',
 100875: 'HDFC Hybrid Equity Fund',
 100876: 'HDFC Income Fund',
 100877: 'HDFC Index Fund',
 100878: 'HDFC Index Fund',
 100881: 'HDFC Infrastructure Fund',
 100899: 'HDFC Large and Mid Cap Fund',
 100900: 'HDFC Liquid Fund',
 100997: 'HDFC Low Duration Fund',
 100998: 'HDFC Medium Term Debt Fund',
 101081: 'HDFC Mid-Cap Opportunities Fund',
 101082: 'HDFC Money Market Fund',
 101083: 'HDFC Multi-Asset Fund',
 101084: 'HDFC Overnight Fund',
 101281: 'HDFC Retirement Savings Fund',
 101282: 'HDFC Retirement Savings Fund',
 101430: 'HDFC Retirement Savings Fund',
 101431: 'HDFC Short Term Debt Fund',
 101480: 'HDFC Small Cap Fund',
 101481: 'HDFC Tax Saver Fund',
 101482: 'HDFC Top 100 Fund',
 101593: 'HSBC Aggressive Hybrid Fund',
 101594: 'HSBC Arbitrage Fund',
 101597: 'HSBC Balanced Advantage Fund',
 101598: 'HSBC Banking and PSU Debt Fund',
 101599: 'HSBC Business Cycles Fund',
 101600: 'HSBC Conservative Hybrid Fund',
 101685: 'HSBC Corporate Bond Fund',
 101686: 'HSBC Corporate Bond Fund',
 101687: 'HSBC Credit Risk Fund',
 101688: 'HSBC Dynamic Bond Fund',
 101691: 'HSBC ELSS Fund',
 101692: 'HSBC Equity Hybrid Fund',
 101693: 'HSBC Equity Savings Fund',
 101694: 'HSBC Flexi Cap Fund',
 101696: 'HSBC Flexi Debt Fund',
 101697: 'HSBC Gilt Fund',
 101698: 'HSBC Infrastructure Fund',
 101699: 'HSBC Large Cap Fund',
 101700: 'HSBC Liquid Fund',
 101701: 'HSBC Low Duration Fund',
 101702: 'HSBC Managed Solutions Conservative Fund',
 102065: 'HSBC Managed Solutions Growth Fund',
 102066: 'HSBC Managed Solutions Moderate Fund',
 102251: 'HSBC Medium Duration Fund',
 102252: 'HSBC Medium to Long Duration Fund',
 102257: 'HSBC Midcap Fund',
 102258: 'HSBC Money Market Fund',
 102259: 'HSBC Short Duration Fund',
 102260: 'HSBC Small Cap Fund',
 102261: 'HSBC Tax Saver Equity Fund',
 102262: 'HSBC Value Fund',
 100348: 'ICICI Pru All Seasons Bond Fund',
 100349: 'ICICI Pru Asset Allocator Fund',
 100350: 'ICICI Pru Balanced Advantage Fund',
 100351: 'ICICI Pru Banking & Financial Services – DirectGrowth',
 100352: 'ICICI Pru Banking & PSU Debt Fund',
 100353: 'ICICI Pru Bluechip Fund',
 100354: 'ICICI Pru Bond Fund',
 100355: 'ICICI Pru Child Care Fund',
 100356: 'ICICI Pru Corporate Bond Fund',
 100357: 'ICICI Pru Credit Risk Fund',
 100358: 'ICICI Pru Debt Management Fund',
 100359: 'ICICI Pru Dividend Yield Equity Fund',
 100360: 'ICICI Pru Equity & Debt Fund',
 100361: 'ICICI Pru Equity – Arbitrage Fund',
 100362: 'ICICI Pru Equity Savings Fund',
 100363: 'ICICI Pru Exports and Services Fund',
 100364: 'ICICI Pru Floating Interest Fund',
 100365: 'ICICI Pru FMCG Fund',
 100366: 'ICICI Pru Focused Equity Fund',
 100367: 'ICICI Pru Gilt Fund',
 100368: 'ICICI Pru Income Optimizer Fund',
 100369: 'ICICI Pru Infrastructure Fund',
 100370: 'ICICI Pru Large & Mid Cap Fund',
 100371: 'ICICI Pru Liquid Fund',
 100372: 'ICICI Pru Long Term Equity Fund',
 100952: 'ICICI Pru Long Term Wealth Enhancement Fund',
 100953: 'ICICI Pru Medium Term Bond Fund',
 100954: 'ICICI Pru MidCap Fund',
 100955: 'ICICI Pru Money Market Fund',
 101098: 'ICICI Pru Multi-Asset Fund',
 101127: 'ICICI Pru Multicap Fund',
 101143: 'ICICI Pru Nifty 50 Index Fund',
 101144: 'ICICI Pru Nifty Next 50 Index Fund',
 101165: 'ICICI Pru Passive Strategy Fund',
 101221: 'ICICI Pru Regular Gold Savings Fund',
 101228: 'ICICI Pru Regular Savings Fund',
 101229: 'ICICI Pru Retirement Fund',
 101230: 'ICICI Pru S&P BSE Sensex Index Fund',
 101231: 'ICICI Pru Savings Fund',
 101349: 'ICICI Pru Short Term Fund',
 101350: 'ICICI Pru Smallcap Fund',
 101351: 'ICICI Pru Technology Fund',
 101617: 'ICICI Pru Thematic Advantage Fund',
 101618: 'ICICI Pru Ultra Short Term Fund',
 101619: 'ICICI Pru Value Discovery Fund',
 113062: 'IDBI Credit Risk Fund',
 113063: 'IDBI Equity Advantage Fund',
 113096: 'IDBI Equity Savings Fund',
 113102: 'IDBI Focused 30 Equity Fund',
 113103: 'IDBI Gold Fund',
 113104: 'IDBI Hybrid Equity Fund',
 113249: 'IDBI India Top 100 Equity Fund',
 113250: 'IDBI Liquid Fund',
 113251: 'IDBI Midcap Fund',
 113252: 'IDBI Nifty 50 Index Fund',
 113253: 'IDBI Nifty Next 50 Index Fund',
 113254: 'IDBI Short Term Bond Fund',
 114630: 'IDBI Small Cap Fund',
 114633: 'IDBI Ultra Short Term Fund',
 122612: 'IIFL Dynamic Bond Fund',
 131579: 'IIFL Focused Equity Fund',
 125337: 'IIFL Liquid Fund',
 115991: 'Indiabulls Arbitrage Fund',
 115992: 'Indiabulls Bluechip Fund',
 115993: 'Indiabulls Liquid Fund',
 115994: 'Indiabulls Short Term Fund',
 115995: 'Indiabulls Tax Savings Fund',
 116424: 'Indiabulls Value Fund',
 104483: 'Invesco India Arbitrage Fund',
 104484: 'Invesco India Banking & PSU Debt Fund',
 104485: 'Invesco India Contra Fund',
 104486: 'Invesco India Corporate Bond Fund',
 104487: 'Invesco India Credit Risk Fund',
 104488: 'Invesco India Dynamic Equity Fund',
 104489: 'Invesco India Financial Services Fund',
 104490: 'Invesco India Gilt Fund',
 104491: 'Invesco India Gold Fund',
 104492: 'Invesco India Growth Opportunities Fund',
 104635: 'Invesco India Infrastructure Fund',
 104636: 'Invesco India Largecap Fund',
 104722: 'Invesco India Liquid Fund',
 104723: 'Invesco India Midcap Fund',
 104724: 'Invesco India Money Market Fund',
 104725: 'Invesco India Multicap Fund',
 104726: 'Invesco India PSU Equity Fund',
 104727: 'Invesco India Short Term Fund',
 104728: 'Invesco India Tax Plan – Direct Growth',
 104729: 'Invesco India Treasury Advantage Fund',
 105024: 'Invesco India Ultra Short Term Fund',
 103780: 'JM Arbitrage Fund',
 101805: 'JM Dynamic Bond Fund',
 100220: 'JM Equity Hybrid Fund',
 120491: 'JM Flexicap Fund',
 120488: 'JM Focused Fund',
 100218: 'JM Large Cap Fund',
 100233: 'JM Liquid Fund',
 143603: 'JM Low Duration Fund',
 100222: 'JM Medium to Long Duration Fund',
 107288: 'JM Tax Gain Fund',
 100254: 'JM Value Fund',
 100261: 'Kotak Banking and PSU Debt Fund',
 100262: 'Kotak Bluechip Fund',
 100263: 'Kotak Bond – Short Term Fund',
 100264: 'Kotak Bond Fund',
 100265: 'Kotak Corporate Bond Fund',
 100278: 'Kotak Credit Risk Fund',
 100279: 'Kotak Debt Hybrid Fund',
 100280: 'Kotak Dynamic Bond Fund',
 100281: 'Kotak Emerging Equity Fund',
 100286: 'Kotak Equity Arbitrage Fund',
 100289: 'Kotak Equity Hybrid Fund',
 100290: 'Kotak Equity Opportunities – Direct Growth',
 100291: 'Kotak Equity Savings Fund',
 100292: 'Kotak Flexi Cap Fund',
 100298: 'Kotak Gilt – Invest Plan – Direct Growth',
 100299: 'Kotak Gilt Invest – PF & Trust Plan – Direct Growth',
 100300: 'Kotak Gold Fund',
 100301: 'Kotak India EQ Contra Fund',
 100828: 'Kotak India Growth Fund',
 100829: 'Kotak Infrastructure & Ecoc. Reform-SP-DirGrowth',
 100830: 'Kotak Liquid Fund',
 100831: 'Kotak Low Duration Fund',
 100832: 'Kotak Medium Term Fund',
 100833: 'Kotak Money Market Fund',
 100834: 'Kotak Multi Asset Allocator FoF – Dynamic – Direct Growth',
 100835: 'Kotak Savings Fund',
 100836: 'Kotak Small Cap Fund',
 101372: 'Kotak Tax Saver Fund',
 118069: 'L&T India Large Cap Fund',
 100312: 'LIC MF Banking & Fina Serv Fund',
 100313: 'LIC MF Banking & PSU Debt Fund',
 100314: 'LIC MF Bond Fund',
 100315: 'LIC MF Children’s Gift Fund',
 100316: 'LIC MF Debt Hybrid Fund',
 100317: 'LIC MF Equity Hybrid Fund',
 100318: 'LIC MF Flexi Cap Fund',
 100319: 'LIC MF G-Sec Fund',
 100321: 'LIC MF Infrastructure Fund',
 100323: 'LIC MF Large & Mid Cap Fund',
 100325: 'LIC MF Large Cap Fund',
 100332: 'LIC MF Liquid Fund',
 100864: 'LIC MF Nifty 50 Index Fund',
 100865: 'LIC MF S&P BSE Sensex Index Fund',
 101184: 'LIC MF Savings Fund',
 101185: 'LIC MF Tax Plan – Direct Growth',
 139534: 'Mahindra Manulife ELSS Fund',
 139535: 'Mahindra Manulife Equity Savings Fund',
 139536: 'Mahindra Manulife Liquid Fund',
 139537: 'Mahindra Manulife Low Duration Fund',
 139538: 'Mahindra Manulife Mid Cap Fund',
 139539: 'Mahindra Manulife Multi Cap Fund',
 107578: 'Mirae Asset Cash Management Fund',
 107579: 'Mirae Asset Dynamic Bond Fund',
 107589: 'Mirae Asset Emerging Bluechip Fund',
 107646: 'Mirae Asset Great Consumer Fund',
 107647: 'Mirae Asset Hybrid – Equity Fund',
 107648: 'Mirae Asset Large Cap Fund',
 107649: 'Mirae Asset Savings Fund',
 107656: 'Mirae Asset Short Term Fund',
 107657: 'Mirae Asset Tax Saver Fund',
 117141: 'Motilal Oswal Balance Advantage Fund',
 122388: 'Motilal Oswal Equity Hybrid Fund',
 122389: 'Motilal Oswal Flexi Cap Fund',
 122390: 'Motilal Oswal Focused Fund',
 124233: 'Motilal Oswal Long Term Equity Fund',
 124303: 'Motilal Oswal Midcap Fund',
 124305: 'Motilal Oswal Ultra Short Term Fund',
 112408: 'Navi 3 In 1 Fund',
 112645: 'Navi Large & Midcap Fund',
 112647: 'Navi Large Cap Equity Fund',
 112648: 'Navi Regular Savings Fund',
 113142: 'Navi Ultra Short Term Fund',
 100379: 'Nippon India Arbitrage Fund',
 100383: 'Nippon India Balanced Advantage Fund',
 100385: 'Nippon India Banking & PSU Debt Fund',
 100386: 'Nippon India Banking&Financial Services-DirGrowth',
 100387: 'Nippon India Consumption Fund',
 100837: 'Nippon India Corporate Bond Fund',
 100838: 'Nippon India Credit Risk Fund',
 100851: 'Nippon India Dynamic Bond Fund',
 100853: 'Nippon India Equity Hybrid Fund',
 100856: 'Nippon India Equity Savings Fund',
 100858: 'Nippon India Floating Rate Fund',
 100859: 'Nippon India Focused Equity Fund',
 101665: 'Nippon India Gold Savings Fund',
 101667: 'Nippon India Growth Fund',
 101862: 'Nippon India GSF – Direct Growth',
 101864: 'Nippon India Hybrid Bond Fund',
 102172: 'Nippon India Income Fund',
 102173: 'Nippon India Index Fund',
 102174: 'Nippon India Index Fund',
 102431: 'Nippon India Large Cap Fund',
 102432: 'Nippon India Liquid Fund',
 102433: 'Nippon India Low Duration Fund',
 102673: 'Nippon India Money Market Fund',
 102675: 'Nippon India Multi Cap Fund',
 102676: 'Nippon India Pharma Fund',
 102677: 'Nippon India Power & Infra Fund',
 102751: 'Nippon India Quant Fund',
 102752: 'Nippon India Retirement Fund',
 102753: 'Nippon India Retirement Fund',
 102848: 'Nippon India Short Term Fund',
 102849: 'Nippon India Small Cap Fund',
 102851: 'Nippon India Strategic Debt Fund',
 103048: 'Nippon India Tax Saver (ELSS) Fund',
 103050: 'Nippon India USD Fund',
 103051: 'Nippon India Value Fund',
 103052: 'Nippon India Vision Fund',
 122640: 'Parag Parikh Flexi Cap Fund',
 116484: 'PGIM India Arbitrage Fund',
 116485: 'PGIM India Banking&PSU Debt Fund',
 120084: 'PGIM India Corporate Bond Fund',
 120086: 'PGIM India Dynamic Bond Fund',
 125305: 'PGIM India Elss Tax Saver Fund',
 125306: 'PGIM India Equity Savings Fund',
 133836: 'PGIM India Flexi Cap Fund',
 133837: 'PGIM India Gilt Fund',
 133838: 'PGIM India Hybrid Equity Fund',
 133839: 'PGIM India Large Cap Fund',
 135598: 'PGIM India Liquid Fund',
 135599: 'PGIM India Low Duration Fund',
 135600: 'PGIM India Midcap Opportunities Fund',
 135601: 'PGIM India Short Duration Fund',
 138254: 'PGIM India Ultra Short Duration Fund',
 100171: 'Quant Absolute Fund',
 100172: 'Quant Active Fund',
 100173: 'Quant Flexi Cap Fund',
 100174: 'Quant Focused Fund',
 100175: 'Quant Infrastructure Fund',
 100176: 'Quant Large and Mid Cap Fund',
 100177: 'Quant Liquid Plan – Direct Growth',
 100630: 'Quant Mid Cap Fund',
 100631: 'Quant Multi Asset Fund',
 101065: 'Quant Small Cap Fund',
 101066: 'Quant Tax Plan- Direct Growth',
 103490: 'Quantum Dynamic Bond Fund',
 103491: 'Quantum Equity Fund',
 103734: 'Quantum Gold Savings Fund',
 103735: 'Quantum Liquid Fund',
 103736: 'Quantum Long Term Equity Value Fund',
 107693: 'Quantum Multi Asset Fund',
 108479: 'Quantum Tax Saving Fund',
 100638: 'SBI Arbitrage Opportunities Fund',
 100639: 'SBI Banking & Financial Services Fund',
 100640: 'SBI Banking and PSU Fund',
 100641: 'SBI BlueChip Fund',
 100643: 'SBI Conservative Hybrid Fund',
 100644: 'SBI Consumption Opportunities Fund',
 100645: 'SBI Contra Fund',
 100717: 'SBI Credit Risk Fund',
 100915: 'SBI Dynamic Bond Fund',
 100917: 'SBI Equity Hybrid Fund',
 100927: 'SBI Equity Savings Fund',
 100928: 'SBI Flexi Cap Fund',
 100929: 'SBI Focused Equity Fund',

In [5]:
# Create a dictionary to map indices to scheme_codes
index_to_scheme_code = dict(zip(data.index, data['Scheme Codes']))

# Example: Get the scheme_code corresponding to index 0
print("Scheme Code for index 0:", index_to_scheme_code)

Scheme Code for index 0: {0: 100033, 1: 100034, 2: 100037, 3: 100038, 4: 100041, 5: 100042, 6: 100043, 7: 100044, 8: 100046, 9: 100047, 10: 100048, 11: 100049, 12: 100051, 13: 100052, 14: 100053, 15: 100054, 16: 100055, 17: 100056, 18: 100057, 19: 100058, 20: 100059, 21: 100060, 22: 100061, 23: 100062, 24: 100063, 25: 100064, 26: 100065, 27: 100066, 28: 100067, 29: 100956, 30: 100970, 31: 100971, 32: 100972, 33: 101313, 34: 101314, 35: 101315, 36: 101316, 37: 101317, 38: 101318, 39: 101591, 40: 112210, 41: 112211, 42: 112212, 43: 112213, 44: 112214, 45: 112215, 46: 112216, 47: 112217, 48: 112277, 49: 112278, 50: 112322, 51: 112323, 52: 112354, 53: 112355, 54: 112369, 55: 112679, 56: 112680, 57: 112681, 58: 112682, 59: 112683, 60: 112684, 61: 112712, 62: 118484, 63: 109255, 64: 109264, 65: 109269, 66: 110606, 67: 110607, 68: 110608, 69: 111585, 70: 111589, 71: 111590, 72: 111709, 73: 111710, 74: 113036, 75: 119333, 76: 119334, 77: 119340, 78: 119354, 79: 119399, 80: 119400, 81: 119415, 82: 119416, 83: 133488, 84: 133517, 85: 133518, 86: 133520, 87: 139344, 88: 140463, 89: 142245, 90: 142246, 91: 100589, 92: 100590, 93: 100593, 94: 100596, 95: 100597, 96: 100600, 97: 100601, 98: 101361, 99: 101362, 100: 101363, 101: 101364, 102: 101365, 103: 101587, 104: 101588, 105: 101589, 106: 101922, 107: 100077, 108: 100078, 109: 100079, 110: 100080, 111: 100081, 112: 100082, 113: 100084, 114: 100085, 115: 100086, 116: 100087, 117: 100088, 118: 100089, 119: 100090, 120: 100940, 121: 100941, 122: 100943, 123: 101303, 124: 101304, 125: 101305, 126: 101306, 127: 101635, 128: 101636, 129: 101742, 130: 101743, 131: 101744, 132: 109934, 133: 109935, 134: 109936, 135: 109937, 136: 109938, 137: 109939, 138: 109940, 139: 109941, 140: 109942, 141: 109944, 142: 109945, 143: 109946, 144: 109949, 145: 109950, 146: 100470, 147: 100471, 148: 100472, 149: 100473, 150: 100481, 151: 100482, 152: 100483, 153: 100484, 154: 100485, 155: 100486, 156: 100487, 157: 100489, 158: 100490, 159: 100491, 160: 100493, 161: 100494, 162: 100495, 163: 100498, 164: 100499, 165: 100503, 166: 100504, 167: 100119, 168: 100120, 169: 100121, 170: 100122, 171: 100123, 172: 100124, 173: 100282, 174: 100283, 175: 100284, 176: 100285, 177: 100868, 178: 100869, 179: 100870, 180: 100871, 181: 100872, 182: 100873, 183: 100874, 184: 100875, 185: 100876, 186: 100877, 187: 100878, 188: 100881, 189: 100899, 190: 100900, 191: 100997, 192: 100998, 193: 101081, 194: 101082, 195: 101083, 196: 101084, 197: 101281, 198: 101282, 199: 101430, 200: 101431, 201: 101480, 202: 101481, 203: 101482, 204: 101593, 205: 101594, 206: 101597, 207: 101598, 208: 101599, 209: 101600, 210: 101685, 211: 101686, 212: 101687, 213: 101688, 214: 101691, 215: 101692, 216: 101693, 217: 101694, 218: 101696, 219: 101697, 220: 101698, 221: 101699, 222: 101700, 223: 101701, 224: 101702, 225: 102065, 226: 102066, 227: 102251, 228: 102252, 229: 102257, 230: 102258, 231: 102259, 232: 102260, 233: 102261, 234: 102262, 235: 100348, 236: 100349, 237: 100350, 238: 100351, 239: 100352, 240: 100353, 241: 100354, 242: 100355, 243: 100356, 244: 100357, 245: 100358, 246: 100359, 247: 100360, 248: 100361, 249: 100362, 250: 100363, 251: 100364, 252: 100365, 253: 100366, 254: 100367, 255: 100368, 256: 100369, 257: 100370, 258: 100371, 259: 100372, 260: 100952, 261: 100953, 262: 100954, 263: 100955, 264: 101098, 265: 101127, 266: 101143, 267: 101144, 268: 101165, 269: 101221, 270: 101228, 271: 101229, 272: 101230, 273: 101231, 274: 101349, 275: 101350, 276: 101351, 277: 101617, 278: 101618, 279: 101619, 280: 113062, 281: 113063, 282: 113096, 283: 113102, 284: 113103, 285: 113104, 286: 113249, 287: 113250, 288: 113251, 289: 113252, 290: 113253, 291: 113254, 292: 114630, 293: 114633, 294: 122612, 295: 131579, 296: 125337, 297: 115991, 298: 115992, 299: 115993, 300: 115994, 301: 115995, 302: 116424, 303: 104483, 304: 104484, 305: 104485, 306: 104486, 307: 104487, 308: 104488, 309: 104489, 310: 104490, 311: 104491, 312: 104492, 313: 104635, 314: 104636, 315: 104722, 316: 104723, 317: 104724, 318: 104725, 319: 104726, 320: 104727, 321: 104728, 322: 104729, 323: 105024, 324: 103780, 325: 101805, 326: 100220, 327: 120491, 328: 120488, 329: 100218, 330: 100233, 331: 143603, 332: 100222, 333: 107288, 334: 100254, 335: 100261, 336: 100262, 337: 100263, 338: 100264, 339: 100265, 340: 100278, 341: 100279, 342: 100280, 343: 100281, 344: 100286, 345: 100289, 346: 100290, 347: 100291, 348: 100292, 349: 100298, 350: 100299, 351: 100300, 352: 100301, 353: 100828, 354: 100829, 355: 100830, 356: 100831, 357: 100832, 358: 100833, 359: 100834, 360: 100835, 361: 100836, 362: 101372, 363: 118069, 364: 100312, 365: 100313, 366: 100314, 367: 100315, 368: 100316, 369: 100317, 370: 100318, 371: 100319, 372: 100321, 373: 100323, 374: 100325, 375: 100332, 376: 100864, 377: 100865, 378: 101184, 379: 101185, 380: 139534, 381: 139535, 382: 139536, 383: 139537, 384: 139538, 385: 139539, 386: 107578, 387: 107579, 388: 107589, 389: 107646, 390: 107647, 391: 107648, 392: 107649, 393: 107656, 394: 107657, 395: 117141, 396: 122388, 397: 122389, 398: 122390, 399: 124233, 400: 124303, 401: 124305, 402: 112408, 403: 112645, 404: 112647, 405: 112648, 406: 113142, 407: 100379, 408: 100383, 409: 100385, 410: 100386, 411: 100387, 412: 100837, 413: 100838, 414: 100851, 415: 100853, 416: 100856, 417: 100858, 418: 100859, 419: 101665, 420: 101667, 421: 101862, 422: 101864, 423: 102172, 424: 102173, 425: 102174, 426: 102431, 427: 102432, 428: 102433, 429: 102673, 430: 102675, 431: 102676, 432: 102677, 433: 102751, 434: 102752, 435: 102753, 436: 102848, 437: 102849, 438: 102851, 439: 103048, 440: 103050, 441: 103051, 442: 103052, 443: 122640, 444: 116484, 445: 116485, 446: 120084, 447: 120086, 448: 125305, 449: 125306, 450: 133836, 451: 133837, 452: 133838, 453: 133839, 454: 135598, 455: 135599, 456: 135600, 457: 135601, 458: 138254, 459: 100171, 460: 100172, 461: 100173, 462: 100174, 463: 100175, 464: 100176, 465: 100177, 466: 100630, 467: 100631, 468: 101065, 469: 101066, 470: 103490, 471: 103491, 472: 103734, 473: 103735, 474: 103736, 475: 107693, 476: 108479, 477: 100638, 478: 100639, 479: 100640, 480: 100641, 481: 100643, 482: 100644, 483: 100645, 484: 100717, 485: 100915, 486: 100917, 487: 100927, 488: 100928, 489: 100929, 490: 100934, 491: 100968, 492: 100999, 493: 101001, 494: 101002, 495: 101003, 496: 101160, 497: 101169, 498: 101206, 499: 101295, 500: 101530, 501: 101551, 502: 101929, 503: 101932, 504: 101933, 505: 101934, 506: 101935, 507: 101950, 508: 101951, 509: 101952, 510: 102030, 511: 102053, 512: 102054, 513: 102055, 514: 102056, 515: 102058, 516: 102061, 517: 102201, 518: 102202, 519: 125711, 520: 100602, 521: 100603, 522: 100604, 523: 100605, 524: 100606, 525: 100607, 526: 100608, 527: 100609, 528: 100610, 529: 100611, 530: 100612, 531: 100613, 532: 100614, 533: 100617, 534: 100618, 535: 100619, 536: 100620, 537: 100621, 538: 100622, 539: 100623, 540: 100780, 541: 100781, 542: 100782, 543: 100783, 544: 100784, 545: 100785, 546: 100786, 547: 100787, 548: 100788, 549: 100414, 550: 100415, 551: 100416, 552: 100417, 553: 100418, 554: 100474, 555: 100475, 556: 101000, 557: 101042, 558: 101049, 559: 101186, 560: 101222, 561: 101224, 562: 101419, 563: 101471, 564: 101489, 565: 101490, 566: 101491, 567: 101547, 568: 101548, 569: 101605, 570: 101606, 571: 101609, 572: 101659, 573: 101672, 574: 100476, 575: 100477, 576: 100480, 577: 101094, 578: 101095, 579: 101113, 580: 101114, 581: 101209, 582: 100496, 583: 100497, 584: 115270, 585: 115290, 586: 115398, 587: 115399, 588: 115400, 589: 115401, 590: 115402, 591: 100381, 592: 100382, 593: 100646, 594: 100648, 595: 100650, 596: 100651, 597: 100656, 598: 100657, 599: 100663, 600: 100664, 601: 100668, 602: 100669, 603: 100678, 604: 100682, 605: 100684, 606: 100685, 607: 100711, 608: 100712, 609: 100723, 610: 100724, 611: 100725, 612: 100739, 613: 100740, 614: 100741, 615: 100742, 616: 100748, 617: 100749, 618: 100750, 619: 100751, 620: 100800, 621: 100801, 622: 100802, 623: 100803, 624: 145963}

In [6]:
unique_values = data['Sub_Category'].unique()
len(unique_values)

36

In [7]:
category_mapping = {unique_values[i]: i+1 for i in range(len(unique_values))}
category_mapping

{'FoFs Domestic': 1,
 'Arbitrage Mutual Funds': 2,
 'Dynamic Asset Allocation or Balanced Advantage': 3,
 'Sectoral / Thematic Mutual Funds': 4,
 'Banking and PSU Mutual Funds': 5,
 'Corporate Bond Mutual Funds': 6,
 'Credit Risk Funds': 7,
 'Dividend Yield Funds': 8,
 'Dynamic Bond': 9,
 'Large & Mid Cap Funds': 10,
 'Aggressive Hybrid Mutual Funds': 11,
 'Equity Savings Mutual Funds': 12,
 'Flexi Cap Funds': 13,
 'Floater Mutual Funds': 14,
 'Focused Funds': 15,
 'Large Cap Mutual Funds': 16,
 'Gilt Mutual Funds': 17,
 'Medium to Long Duration Funds': 18,
 'Liquid Mutual Funds': 19,
 'Low Duration Funds': 20,
 'Medium Duration Funds': 21,
 'Mid Cap Mutual Funds': 22,
 'Money Market Funds': 23,
 'Index Funds': 24,
 'Value Funds': 25,
 'Conservative Hybrid Mutual Funds': 26,
 'Ultra Short Duration Funds': 27,
 'Short Duration Funds': 28,
 'Small Cap Mutual Funds': 29,
 'ELSS Mutual Funds': 30,
 'Childrens Funds': 31,
 'Multi Asset Allocation Mutual Funds': 32,
 'Multi Cap Funds': 33,
 'Overnight Mutual Funds': 34,
 'Retirement Funds': 35,
 'Contra Funds': 36}

## User Input

In [8]:
def calculate_expense_ratio(investment_budget):
    # Define expense ratio range for the Indian market (0.01 to 0.05)
    min_expense_ratio = 0.01
    max_expense_ratio = 0.05
    
    # Normalize investment budget between 0 and 1
    normalized_budget = investment_budget / 10000  # Assuming maximum investment budget is 500000 INR
    
    # Calculate normalized expense ratio within the range
    normalized_expense_ratio = min_expense_ratio + (max_expense_ratio - min_expense_ratio) * normalized_budget
    
    # Apply bias to expense ratio
    biased_expense_ratio = normalized_expense_ratio
    
    # If expense ratio is greater than 0.5, set it to 0.5
    if biased_expense_ratio > 0.5:
        biased_expense_ratio = 0.5
    
    return biased_expense_ratio

In [9]:
# Works only on yearly income
def calculate_risk(age, income):
    if age <= 30:
        if income >= 1000000:
            return 0.5
        elif income >= 700000:
            return 0.4
        elif income >= 500000:
            return 0.3
        else:
            return 0.2
    elif age <= 40:
        if income >= 1200000:
            return 0.4
        elif income >= 800000:
            return 0.3
        elif income >= 600000:
            return 0.2
        else:
            return 0.1
    elif age <= 50:
        if income >= 1500000:
            return 0.3
        elif income >= 1000000:
            return 0.2
        elif income >= 800000:
            return 0.1
        else:
            return 0
    else:
        if income >= 2000000:
            return 0.2
        elif income >= 1500000:
            return 0.1
        else:
            return 0

In [10]:
def normalize_risk(risk):
    # Normalize risk value between 0 and 1
    normalized_risk = risk
    
    # Apply bias to expense ratio
    biased_normalized_risk = normalized_risk
    
    # If expense ratio is greater than 0.5, set it to 0.5
    if biased_normalized_risk > 0.25:
        biased_normalized_risk = 0.25
    
    return biased_normalized_risk

In [11]:
def get_user_inputs():
    age = int(input("Enter your age: "))
    income = float(input("Enter your income: "))
    investment_budget = float(input("Enter your investment budget: "))
    
    subcategories = []
    while True:
        subcategory = input("Enter a subcategory (or type 'done' to finish): ")
        if subcategory.lower() == 'done':
            break
        subcategories.append(float(subcategory))  # Convert input to float and append to list
    
    investment_term = input("Enter the investment term (short term, midterm, or high term): ")
    investment_term_map = {'short term': 1, 'midterm': 3, 'high term': 5}
    investment_term_numeric = investment_term_map.get(investment_term.lower(), None)
    
    return age, income, investment_budget, subcategories, investment_term_numeric

# Example usage:
age, income, investment_budget, subcategories, investment_term = get_user_inputs()
print("Age:", age)
print("Income:", income)
print("Investment Budget:", investment_budget)
print("Subcategories:", subcategories)
print("Investment Term:", investment_term)

Enter your age:  25
Enter your income:  1000000
Enter your investment budget:  100000
Enter a subcategory (or type 'done' to finish):  done
Enter the investment term (short term, midterm, or high term):  short term

Age: 25
Income: 1000000.0
Investment Budget: 100000.0
Subcategories: []
Investment Term: 1

In [12]:
def calculate_user_vector(age, income, investment_budget):
    expense_ratio = calculate_expense_ratio(investment_budget)
    risk = calculate_risk(age, income)
    normalised_risk = normalize_risk(risk)
    return [expense_ratio, normalised_risk]

In [13]:
vector = calculate_user_vector(age, income, investment_budget)
print("Vector:", vector)

Vector: [0.41000000000000003, 0.25]

## Filtering

In [14]:
# Assuming you have already created the category_mapping dictionary
# Reverse the dictionary to map integers back to category names
reverse_category_mapping = {v: k for k, v in category_mapping.items()}

# Assuming you have already created the reverse_category_mapping dictionary
# Assuming you have an array of values called values

category_names = []

if len(subcategories) == 0:
    # If subcategories is empty, copy unique values to category_names
    category_names = unique_values
else:
    values = subcategories # Example array of values
    # Create an empty list to store the category names
    # Loop through the array of values and get the corresponding category names
    for value in values:
        category_name = reverse_category_mapping.get(value, "Unknown")
        category_names.append(category_name)

print(category_names)

['FoFs Domestic' 'Arbitrage Mutual Funds'
 'Dynamic Asset Allocation or Balanced Advantage'
 'Sectoral / Thematic Mutual Funds' 'Banking and PSU Mutual Funds'
 'Corporate Bond Mutual Funds' 'Credit Risk Funds' 'Dividend Yield Funds'
 'Dynamic Bond' 'Large & Mid Cap Funds' 'Aggressive Hybrid Mutual Funds'
 'Equity Savings Mutual Funds' 'Flexi Cap Funds' 'Floater Mutual Funds'
 'Focused Funds' 'Large Cap Mutual Funds' 'Gilt Mutual Funds'
 'Medium to Long Duration Funds' 'Liquid Mutual Funds'
 'Low Duration Funds' 'Medium Duration Funds' 'Mid Cap Mutual Funds'
 'Money Market Funds' 'Index Funds' 'Value Funds'
 'Conservative Hybrid Mutual Funds' 'Ultra Short Duration Funds'
 'Short Duration Funds' 'Small Cap Mutual Funds' 'ELSS Mutual Funds'
 'Childrens Funds' 'Multi Asset Allocation Mutual Funds' 'Multi Cap Funds'
 'Overnight Mutual Funds' 'Retirement Funds' 'Contra Funds']

This is the new dataset after filtering

In [15]:
filtered_df = data[data['Sub_Category'].isin(category_names)]
filtered_df

,scheme_name,Scheme Codes,expense_ratio,risk_level,returns_1yr,returns_3yr,returns_5yr,Sub_Category
0,Aditya Birla SL Active Debt Multi-Mgr FoF-Dir ...,100033,0.27,0.2,4.0,6.5,6.9,FoFs Domestic
1,Aditya Birla SL Arbitrage Fund,100034,0.36,0.0,5.6,4.8,5.5,Arbitrage Mutual Funds
2,Aditya Birla SL Asset Allocator FoF-Dir Growth,100037,0.53,0.4,2.0,18.9,9.7,FoFs Domestic
3,Aditya Birla SL Balanced Advantage Fund,100038,0.61,0.5,4.5,18.6,9.7,Dynamic Asset Allocation or Balanced Advantage
4,Aditya Birla SL Banking&Financial Services-Dir...,100041,1.17,0.5,5.3,24.6,9.2,Sectoral / Thematic Mutual Funds
...,...,...,...,...,...,...,...,...
620,UTI-Treasury Advantage Fund,100800,0.33,0.1,5.2,7.3,4.8,Low Duration Funds
621,UTI-Ultra Short Term Fund,100801,0.44,0.2,5.4,6.1,5.7,Ultra Short Duration Funds
622,UTI-Unit Linked Insurance Plan – Direct,100802,0.96,0.3,-0.7,13.1,6.2,Dynamic Asset Allocation or Balanced Advantage
623,UTI-Value Opportunities Fund,100803,1.16,0.5,1.7,27.2,12.2,Value Funds
624,WhiteOak Capital Overnight Fund,145963,0.22,0.0,1.7,32.4,13.3,Overnight Mutual Funds

In [16]:
columns_to_drop = ['scheme_name', 'Scheme Codes', 'returns_3yr', 'returns_5yr']
first_year_returns_data = filtered_df.drop(columns=columns_to_drop)
first_year_returns_data

,expense_ratio,risk_level,returns_1yr,Sub_Category
0,0.27,0.2,4.0,FoFs Domestic
1,0.36,0.0,5.6,Arbitrage Mutual Funds
2,0.53,0.4,2.0,FoFs Domestic
3,0.61,0.5,4.5,Dynamic Asset Allocation or Balanced Advantage
4,1.17,0.5,5.3,Sectoral / Thematic Mutual Funds
...,...,...,...,...
620,0.33,0.1,5.2,Low Duration Funds
621,0.44,0.2,5.4,Ultra Short Duration Funds
622,0.96,0.3,-0.7,Dynamic Asset Allocation or Balanced Advantage
623,1.16,0.5,1.7,Value Funds
624,0.22,0.0,1.7,Overnight Mutual Funds

In [17]:
columns_to_drop = ['scheme_name', 'Scheme Codes', 'returns_1yr', 'returns_5yr']
third_year_returns_data = filtered_df.drop(columns=columns_to_drop)
third_year_returns_data

,expense_ratio,risk_level,returns_3yr,Sub_Category
0,0.27,0.2,6.5,FoFs Domestic
1,0.36,0.0,4.8,Arbitrage Mutual Funds
2,0.53,0.4,18.9,FoFs Domestic
3,0.61,0.5,18.6,Dynamic Asset Allocation or Balanced Advantage
4,1.17,0.5,24.6,Sectoral / Thematic Mutual Funds
...,...,...,...,...
620,0.33,0.1,7.3,Low Duration Funds
621,0.44,0.2,6.1,Ultra Short Duration Funds
622,0.96,0.3,13.1,Dynamic Asset Allocation or Balanced Advantage
623,1.16,0.5,27.2,Value Funds
624,0.22,0.0,32.4,Overnight Mutual Funds

In [18]:
columns_to_drop = ['scheme_name', 'Scheme Codes', 'returns_1yr', 'returns_3yr']
fifth_year_returns_data = filtered_df.drop(columns=columns_to_drop)
fifth_year_returns_data

,expense_ratio,risk_level,returns_5yr,Sub_Category
0,0.27,0.2,6.9,FoFs Domestic
1,0.36,0.0,5.5,Arbitrage Mutual Funds
2,0.53,0.4,9.7,FoFs Domestic
3,0.61,0.5,9.7,Dynamic Asset Allocation or Balanced Advantage
4,1.17,0.5,9.2,Sectoral / Thematic Mutual Funds
...,...,...,...,...
620,0.33,0.1,4.8,Low Duration Funds
621,0.44,0.2,5.7,Ultra Short Duration Funds
622,0.96,0.3,6.2,Dynamic Asset Allocation or Balanced Advantage
623,1.16,0.5,12.2,Value Funds
624,0.22,0.0,13.3,Overnight Mutual Funds

In [19]:
if investment_term == 1:
    # Copy data1 to a new DataFrame
    returns_data = first_year_returns_data.copy()
    user_data = {
    'expense_ratio': [vector[0]],
    'risk_level': [vector[1]],
    'returns_1yr': [0.75]
}
elif investment_term == 3:
    returns_data = third_year_returns_data.copy()
    user_data = {
    'expense_ratio': [vector[0]],
    'risk_level': [vector[1]],
    'returns_3yr': [0.75]
}
elif investment_term == 5:
    returns_data = fifth_year_returns_data.copy()
    user_data = {
    'expense_ratio': [vector[0]],
    'risk_level': [vector[1]],
    'returns_5yr': [0.75]
}
else:
    print("Invalid value. Please enter 1 or 3 or 5.")

In [20]:
returns_data

,expense_ratio,risk_level,returns_1yr,Sub_Category
0,0.27,0.2,4.0,FoFs Domestic
1,0.36,0.0,5.6,Arbitrage Mutual Funds
2,0.53,0.4,2.0,FoFs Domestic
3,0.61,0.5,4.5,Dynamic Asset Allocation or Balanced Advantage
4,1.17,0.5,5.3,Sectoral / Thematic Mutual Funds
...,...,...,...,...
620,0.33,0.1,5.2,Low Duration Funds
621,0.44,0.2,5.4,Ultra Short Duration Funds
622,0.96,0.3,-0.7,Dynamic Asset Allocation or Balanced Advantage
623,1.16,0.5,1.7,Value Funds
624,0.22,0.0,1.7,Overnight Mutual Funds

In [21]:
columns_to_drop = ['Sub_Category']
returns_data =  returns_data.drop(columns=columns_to_drop)
returns_data

     expense_ratio  risk_level  returns_1yr
0             0.27         0.2          4.0
1             0.36         0.0          5.6
2             0.53         0.4          2.0
3             0.61         0.5          4.5
4             1.17         0.5          5.3
..             ...         ...          ...
620           0.33         0.1          5.2
621           0.44         0.2          5.4
622           0.96         0.3         -0.7
623           1.16         0.5          1.7
624           0.22         0.0          1.7

[625 rows x 3 columns]

In [22]:
# Assuming df is your DataFrame
index_to_row_number = {index: row_number for row_number, index in enumerate(returns_data.index)}

# Example usage:
print(index_to_row_number)

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13, 14: 14, 15: 15, 16: 16, 17: 17, 18: 18, 19: 19, 20: 20, 21: 21, 22: 22, 23: 23, 24: 24, 25: 25, 26: 26, 27: 27, 28: 28, 29: 29, 30: 30, 31: 31, 32: 32, 33: 33, 34: 34, 35: 35, 36: 36, 37: 37, 38: 38, 39: 39, 40: 40, 41: 41, 42: 42, 43: 43, 44: 44, 45: 45, 46: 46, 47: 47, 48: 48, 49: 49, 50: 50, 51: 51, 52: 52, 53: 53, 54: 54, 55: 55, 56: 56, 57: 57, 58: 58, 59: 59, 60: 60, 61: 61, 62: 62, 63: 63, 64: 64, 65: 65, 66: 66, 67: 67, 68: 68, 69: 69, 70: 70, 71: 71, 72: 72, 73: 73, 74: 74, 75: 75, 76: 76, 77: 77, 78: 78, 79: 79, 80: 80, 81: 81, 82: 82, 83: 83, 84: 84, 85: 85, 86: 86, 87: 87, 88: 88, 89: 89, 90: 90, 91: 91, 92: 92, 93: 93, 94: 94, 95: 95, 96: 96, 97: 97, 98: 98, 99: 99, 100: 100, 101: 101, 102: 102, 103: 103, 104: 104, 105: 105, 106: 106, 107: 107, 108: 108, 109: 109, 110: 110, 111: 111, 112: 112, 113: 113, 114: 114, 115: 115, 116: 116, 117: 117, 118: 118, 119: 119, 120: 120, 121: 121, 122: 122, 123: 123, 124: 124, 125: 125, 126: 126, 127: 127, 128: 128, 129: 129, 130: 130, 131: 131, 132: 132, 133: 133, 134: 134, 135: 135, 136: 136, 137: 137, 138: 138, 139: 139, 140: 140, 141: 141, 142: 142, 143: 143, 144: 144, 145: 145, 146: 146, 147: 147, 148: 148, 149: 149, 150: 150, 151: 151, 152: 152, 153: 153, 154: 154, 155: 155, 156: 156, 157: 157, 158: 158, 159: 159, 160: 160, 161: 161, 162: 162, 163: 163, 164: 164, 165: 165, 166: 166, 167: 167, 168: 168, 169: 169, 170: 170, 171: 171, 172: 172, 173: 173, 174: 174, 175: 175, 176: 176, 177: 177, 178: 178, 179: 179, 180: 180, 181: 181, 182: 182, 183: 183, 184: 184, 185: 185, 186: 186, 187: 187, 188: 188, 189: 189, 190: 190, 191: 191, 192: 192, 193: 193, 194: 194, 195: 195, 196: 196, 197: 197, 198: 198, 199: 199, 200: 200, 201: 201, 202: 202, 203: 203, 204: 204, 205: 205, 206: 206, 207: 207, 208: 208, 209: 209, 210: 210, 211: 211, 212: 212, 213: 213, 214: 214, 215: 215, 216: 216, 217: 217, 218: 218, 219: 219, 220: 220, 221: 221, 222: 222, 223: 223, 224: 224, 225: 225, 226: 226, 227: 227, 228: 228, 229: 229, 230: 230, 231: 231, 232: 232, 233: 233, 234: 234, 235: 235, 236: 236, 237: 237, 238: 238, 239: 239, 240: 240, 241: 241, 242: 242, 243: 243, 244: 244, 245: 245, 246: 246, 247: 247, 248: 248, 249: 249, 250: 250, 251: 251, 252: 252, 253: 253, 254: 254, 255: 255, 256: 256, 257: 257, 258: 258, 259: 259, 260: 260, 261: 261, 262: 262, 263: 263, 264: 264, 265: 265, 266: 266, 267: 267, 268: 268, 269: 269, 270: 270, 271: 271, 272: 272, 273: 273, 274: 274, 275: 275, 276: 276, 277: 277, 278: 278, 279: 279, 280: 280, 281: 281, 282: 282, 283: 283, 284: 284, 285: 285, 286: 286, 287: 287, 288: 288, 289: 289, 290: 290, 291: 291, 292: 292, 293: 293, 294: 294, 295: 295, 296: 296, 297: 297, 298: 298, 299: 299, 300: 300, 301: 301, 302: 302, 303: 303, 304: 304, 305: 305, 306: 306, 307: 307, 308: 308, 309: 309, 310: 310, 311: 311, 312: 312, 313: 313, 314: 314, 315: 315, 316: 316, 317: 317, 318: 318, 319: 319, 320: 320, 321: 321, 322: 322, 323: 323, 324: 324, 325: 325, 326: 326, 327: 327, 328: 328, 329: 329, 330: 330, 331: 331, 332: 332, 333: 333, 334: 334, 335: 335, 336: 336, 337: 337, 338: 338, 339: 339, 340: 340, 341: 341, 342: 342, 343: 343, 344: 344, 345: 345, 346: 346, 347: 347, 348: 348, 349: 349, 350: 350, 351: 351, 352: 352, 353: 353, 354: 354, 355: 355, 356: 356, 357: 357, 358: 358, 359: 359, 360: 360, 361: 361, 362: 362, 363: 363, 364: 364, 365: 365, 366: 366, 367: 367, 368: 368, 369: 369, 370: 370, 371: 371, 372: 372, 373: 373, 374: 374, 375: 375, 376: 376, 377: 377, 378: 378, 379: 379, 380: 380, 381: 381, 382: 382, 383: 383, 384: 384, 385: 385, 386: 386, 387: 387, 388: 388, 389: 389, 390: 390, 391: 391, 392: 392, 393: 393, 394: 394, 395: 395, 396: 396, 397: 397, 398: 398, 399: 399, 400: 400, 401: 401, 402: 402, 403: 403, 404: 404, 405: 405, 406: 406, 407: 407, 408: 408, 409: 409, 410: 410, 411: 411, 412: 412, 413: 413, 414: 414, 415: 415, 416: 416, 417: 417, 418: 418, 419: 419, 420: 420, 421: 421, 422: 422, 423: 423, 424: 424, 425: 425, 426: 426, 427: 427, 428: 428, 429: 429, 430: 430, 431: 431, 432: 432, 433: 433, 434: 434, 435: 435, 436: 436, 437: 437, 438: 438, 439: 439, 440: 440, 441: 441, 442: 442, 443: 443, 444: 444, 445: 445, 446: 446, 447: 447, 448: 448, 449: 449, 450: 450, 451: 451, 452: 452, 453: 453, 454: 454, 455: 455, 456: 456, 457: 457, 458: 458, 459: 459, 460: 460, 461: 461, 462: 462, 463: 463, 464: 464, 465: 465, 466: 466, 467: 467, 468: 468, 469: 469, 470: 470, 471: 471, 472: 472, 473: 473, 474: 474, 475: 475, 476: 476, 477: 477, 478: 478, 479: 479, 480: 480, 481: 481, 482: 482, 483: 483, 484: 484, 485: 485, 486: 486, 487: 487, 488: 488, 489: 489, 490: 490, 491: 491, 492: 492, 493: 493, 494: 494, 495: 495, 496: 496, 497: 497, 498: 498, 499: 499, 500: 500, 501: 501, 502: 502, 503: 503, 504: 504, 505: 505, 506: 506, 507: 507, 508: 508, 509: 509, 510: 510, 511: 511, 512: 512, 513: 513, 514: 514, 515: 515, 516: 516, 517: 517, 518: 518, 519: 519, 520: 520, 521: 521, 522: 522, 523: 523, 524: 524, 525: 525, 526: 526, 527: 527, 528: 528, 529: 529, 530: 530, 531: 531, 532: 532, 533: 533, 534: 534, 535: 535, 536: 536, 537: 537, 538: 538, 539: 539, 540: 540, 541: 541, 542: 542, 543: 543, 544: 544, 545: 545, 546: 546, 547: 547, 548: 548, 549: 549, 550: 550, 551: 551, 552: 552, 553: 553, 554: 554, 555: 555, 556: 556, 557: 557, 558: 558, 559: 559, 560: 560, 561: 561, 562: 562, 563: 563, 564: 564, 565: 565, 566: 566, 567: 567, 568: 568, 569: 569, 570: 570, 571: 571, 572: 572, 573: 573, 574: 574, 575: 575, 576: 576, 577: 577, 578: 578, 579: 579, 580: 580, 581: 581, 582: 582, 583: 583, 584: 584, 585: 585, 586: 586, 587: 587, 588: 588, 589: 589, 590: 590, 591: 591, 592: 592, 593: 593, 594: 594, 595: 595, 596: 596, 597: 597, 598: 598, 599: 599, 600: 600, 601: 601, 602: 602, 603: 603, 604: 604, 605: 605, 606: 606, 607: 607, 608: 608, 609: 609, 610: 610, 611: 611, 612: 612, 613: 613, 614: 614, 615: 615, 616: 616, 617: 617, 618: 618, 619: 619, 620: 620, 621: 621, 622: 622, 623: 623, 624: 624}

### normalisation

In [23]:
from sklearn.preprocessing import MinMaxScaler

column_to_exclude='risk_level'
column_data = returns_data['risk_level']

data_to_normalize = returns_data.drop(columns=[column_to_exclude])
# Initialize MinMaxScaler
scaler = MinMaxScaler()

# Fit the scaler to the data and transform the data
returns_data_normalized = scaler.fit_transform(data_to_normalize)

# Convert the scaled data back to a DataFrame
normalized_df = pd.DataFrame(returns_data_normalized, columns=data_to_normalize.columns)
returns_data_normalized = pd.concat([normalized_df, column_data], axis=1)

In [24]:
returns_data_normalized

     expense_ratio  returns_1yr  risk_level
0         0.083004     0.157475         0.2
1         0.118577     0.168106         0.0
2         0.185771     0.144186         0.4
3         0.217391     0.160797         0.5
4         0.438735     0.166113         0.5
..             ...          ...         ...
620       0.106719     0.165449         0.1
621       0.150198     0.166777         0.2
622       0.355731     0.126246         0.3
623       0.434783     0.142193         0.5
624       0.063241     0.142193         0.0

[625 rows x 3 columns]

In [25]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity

In [26]:
user_df = pd.DataFrame(user_data)

# Append the user input data to the original DataFrame
returns_data_with_user = pd.concat([returns_data_normalized, user_df], ignore_index=True)

# Now your data DataFrame contains the user input data as a new row
print("Updated DataFrame:")
returns_data_with_user

Updated DataFrame:

     expense_ratio  returns_1yr  risk_level
0         0.083004     0.157475        0.20
1         0.118577     0.168106        0.00
2         0.185771     0.144186        0.40
3         0.217391     0.160797        0.50
4         0.438735     0.166113        0.50
..             ...          ...         ...
621       0.150198     0.166777        0.20
622       0.355731     0.126246        0.30
623       0.434783     0.142193        0.50
624       0.063241     0.142193        0.00
625       0.410000     0.750000        0.25

[626 rows x 3 columns]

## Cosine Similarity

In [27]:
# Calculate cosine similarity
returns_data_similarity = cosine_similarity(returns_data_with_user)

# Convert cosine similarity array to DataFrame for readability
returns_data_similarity = pd.DataFrame(returns_data_similarity, columns=returns_data_with_user.index, index=returns_data_with_user.index)

print("Cosine Similarity Matrix:")
returns_data_similarity

Cosine Similarity Matrix:

,0,1,2,3,4,5,6,7,8,9,...,616,617,618,619,620,621,622,623,624,625
0,1.000000,0.659307,0.950818,0.941985,0.885614,0.991484,0.934464,0.951814,0.827544,0.803219,...,0.808269,0.886704,0.996932,0.933519,0.928759,0.978130,0.847479,0.873425,0.663377,0.847736
1,0.659307,1.000000,0.484699,0.451599,0.566826,0.710415,0.883719,0.687374,0.359420,0.616128,...,0.686734,0.618230,0.699003,0.604743,0.890819,0.741325,0.639218,0.541263,0.980885,0.953555
2,0.950818,0.484699,1.000000,0.999297,0.960149,0.954496,0.818938,0.962611,0.957275,0.885326,...,0.865275,0.947530,0.950951,0.978192,0.816697,0.945938,0.913111,0.958097,0.446626,0.688017
3,0.941985,0.451599,0.999297,1.000000,0.954729,0.943363,0.797740,0.952325,0.960665,0.876045,...,0.852593,0.939643,0.940320,0.971684,0.795107,0.933203,0.903513,0.953702,0.413883,0.661226
4,0.885614,0.566826,0.960149,0.954729,1.000000,0.925599,0.815225,0.978517,0.972218,0.979837,...,0.967281,0.997720,0.907243,0.993239,0.821030,0.939288,0.989287,0.999435,0.481415,0.703361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
621,0.978130,0.741325,0.945938,0.933203,0.939288,0.996858,0.958173,0.989700,0.860182,0.896117,...,0.907239,0.948395,0.991285,0.969931,0.958394,1.000000,0.927805,0.927800,0.709934,0.883988
622,0.847479,0.639218,0.913111,0.903513,0.989287,0.903526,0.825246,0.969147,0.936782,0.996906,...,0.993952,0.995504,0.879517,0.975871,0.834494,0.927805,1.000000,0.987336,0.539053,0.734830
623,0.873425,0.541263,0.958097,0.953702,0.999435,0.913975,0.795345,0.971254,0.978440,0.979586,...,0.964207,0.995494,0.894952,0.989685,0.801387,0.927800,0.987336,1.000000,0.452435,0.679192
624,0.663377,0.980885,0.446626,0.413883,0.481415,0.691743,0.878983,0.631686,0.272567,0.503074,...,0.577357,0.531584,0.690781,0.539701,0.880980,0.709934,0.539053,0.452435,1.000000,0.956580
625,0.847736,0.953555,0.688017,0.661226,0.703361,0.871992,0.979705,0.825996,0.533015,0.696624,...,0.750344,0.739950,0.870035,0.756474,0.980606,0.883988,0.734830,0.679192,0.956580,1.000000

In [28]:
user_similarity=returns_data_similarity[len(returns_data_similarity)-1]

In [29]:
user_similarity

0      0.847736
1      0.953555
2      0.688017
3      0.661226
4      0.703361
         ...
621    0.883988
622    0.734830
623    0.679192
624    0.956580
625    1.000000
Name: 625, Length: 626, dtype: float64

In [30]:
import numpy as np

# Exclude the last element of the array
array_without_last = user_similarity[:-1]

# Get the indices of the top 10 largest values
top_10_indices = np.argpartition(-array_without_last, kth=10)[:10]

# Print the indices of the top 10 largest values
print("Indices of the top 10 largest values:")
print(top_10_indices)

Indices of the top 10 largest values:
[243 535  65 131 620 455 509 465 104 120]

In [31]:
# Assuming you have already created the category_mapping dictionary
# Reverse the dictionary to map integers back to category names
reverse_category_mapping = {v: k for k, v in index_to_row_number.items()}

# Assuming you have already created the reverse_category_mapping dictionary
# Assuming you have an array of values called values

# Create an empty list to store the category names
scheme_index = []

# Loop through the array of values and get the corresponding category names
for value in top_10_indices:
    index = reverse_category_mapping.get(value, "Unknown")
    scheme_index.append(index)

print(scheme_index)

[243, 535, 65, 131, 620, 455, 509, 465, 104, 120]

In [32]:
scheme_codes = []
for key in scheme_index:
    code = index_to_scheme_code.get(key)
    scheme_codes.append(code)

print(scheme_codes)

[100356, 100619, 109269, 101744, 100800, 135599, 101952, 100177, 101588, 100940]

## Prediction

In [33]:
import requests
import pandas as pd
from prophet import Prophet

Importing plotly failed. Interactive plots will not work.

In [34]:
# Function create a dataframe by fetching the current data.import requests
def fetch_scheme_nav_data(scheme_code):
    api_url = f"https://api.mfapi.in/mf/{scheme_code}"
    response = requests.get(api_url)
    
    if response.status_code == 200:
        json_data = response.json()
        nav_data = json_data.get('data', [])
        
        if nav_data:
            nav_df = pd.DataFrame(nav_data)
            nav_df['date'] = pd.to_datetime(nav_df['date'], format='%d-%m-%Y')
            nav_df['nav'] = pd.to_numeric(nav_df['nav'], errors='coerce')
            nav_df['date'] = nav_df['date'].dt.strftime('%d-%m-%Y')
            nav_df = nav_df[::-1]
            return nav_df
        else:
            print("No NAV data available for the scheme.")
            return None
    else:
        print("Failed to fetch JSON data:", response.status_code)
        return None

In [35]:
# Function to predcit and return the predcited dataframe
def predict_nav(nav_df):
    
    # Check if the dataframe is small
    if len(nav_df) < 100:
        #print("Input dataframe is too small. Returning null dataframe.")
        return pd.DataFrame(columns=['ds', 'yhat'])
    # Step 1: Preprocess the data
    # Ensure 'date' column is in datetime format
    nav_df['ds'] = pd.to_datetime(nav_df['date'], format='%d-%m-%Y')
    # Rename 'nav' column to 'y' as required by Prophet
    nav_df.rename(columns={'nav': 'y'}, inplace=True)

    # Step 2: Train a forecasting model
    model = Prophet()
    model.fit(nav_df)

    # Step 3: Make predictions for the next 5 years
    future = model.make_future_dataframe(periods=365*5, freq='D')
    forecast = model.predict(future)
    
    # Filter out dates beyond the range of the original data
    future_dates = forecast[forecast['ds'] > nav_df['ds'].max()]['ds']

    # Create predicted_values DataFrame with only future dates and predicted NAV values
    predicted_values = forecast[forecast['ds'].isin(future_dates)][['ds', 'yhat']].copy()

    return predicted_values

In [36]:
# Function which will return the scores based on the predicted value
def calculate_returns(predicted_nav_df):    
    
    if predicted_nav_df.empty:  # Check if the dataframe is empty
        return {}  # Return an empty dataframe if it's empty
    # Step 1: Sort the dataframe by date
    
    predicted_nav_df_sorted = predicted_nav_df.sort_values(by='ds')

    # Step 2: Calculate 1-year, 3-year, and 5-year returns
    def calculate_returns(nav_values, dates, years):
        returns = {}
        for year in years:
            # Calculate the NAV at the beginning and end of the period
            end_nav = nav_values.iloc[-1]
            start_date = max(dates) - pd.DateOffset(years=year)
            start_nav = nav_values[dates >= start_date].iloc[0]
                        # If start_nav is zero, replace it with 1
            if start_nav == 0:
                start_nav = 1
            # Calculate the return using the CAGR formula
            cagr = (end_nav / start_nav) ** (1/year) - 1
            returns[f"{year}-Year Return"] = cagr * 100  # Convert to percentage
        return returns

    # Extract NAV values and dates
    nav_values = predicted_nav_df_sorted['yhat']
    dates = predicted_nav_df_sorted['ds']

    # Calculate returns
    years = [1, 3, 5]
    returns = calculate_returns(nav_values, dates, years)

    return returns

In [37]:
# Function to create a dataframe with funds and scores
def calculate_scores_for_scheme_codes(scheme_codes, year):
    # Create an empty list to store the results
    results = []

    # Iterate over the list of scheme codes
    for scheme_code in scheme_codes:
        # Fetch NAV data for the scheme
        nav_df = fetch_scheme_nav_data(scheme_code)

        if nav_df is not None:
            # Predict NAV values
            predicted_nav_df = predict_nav(nav_df)

            # Calculate returns
            returns = calculate_returns(predicted_nav_df)
            #print(type(returns_dict))
            if not returns:
                results.append({
                    'Scheme Code': scheme_code,
                    '1-Year Return': -1,
                    '3-Year Return': -1,
                    '5-Year Return': -1
                })
            else:
                # Append scheme code and returns to the results list as a dictionary
                results.append({
                    'Scheme Code': scheme_code,
                    '1-Year Return': returns['1-Year Return'],
                    '3-Year Return': returns['3-Year Return'],
                    '5-Year Return': returns['5-Year Return']
                })
        else:
            print(f"Failed to fetch NAV data for scheme code {scheme_code}. Skipping...")

    # Create DataFrame from the list of dictionaries
    results_df = pd.DataFrame(results)

    returns = {}
    for index, row in results_df.iterrows():
        scheme_code = row['Scheme Code']
        if year == 1:
            returns[scheme_code] = row['1-Year Return']
        elif year == 3:
            returns[scheme_code] = row['3-Year Return']
        elif year == 5:
            returns[scheme_code] = row['5-Year Return']
        else:
            print("Invalid year! Please provide 1, 3, or 5 for year.")
            return None
    return returns

investment_term  scheme_codes

In [38]:
scores_df = calculate_scores_for_scheme_codes(scheme_codes,investment_term)
scores_df

14:57:24 - cmdstanpy - INFO - Chain [1] start processing
14:57:26 - cmdstanpy - INFO - Chain [1] done processing
14:57:29 - cmdstanpy - INFO - Chain [1] start processing
14:57:34 - cmdstanpy - INFO - Chain [1] done processing
14:57:38 - cmdstanpy - INFO - Chain [1] start processing
14:57:40 - cmdstanpy - INFO - Chain [1] done processing
14:57:43 - cmdstanpy - INFO - Chain [1] start processing
14:57:44 - cmdstanpy - INFO - Chain [1] done processing
14:57:45 - cmdstanpy - INFO - Chain [1] start processing
14:57:45 - cmdstanpy - INFO - Chain [1] done processing
C:\Users\SOUVIK GHOSH\AppData\Local\Temp\ipykernel_1628\3114556751.py:22: RuntimeWarning: invalid value encountered in scalar power
  cagr = (end_nav / start_nav) ** (1/year) - 1
14:57:47 - cmdstanpy - INFO - Chain [1] start processing
14:57:49 - cmdstanpy - INFO - Chain [1] done processing
14:57:51 - cmdstanpy - INFO - Chain [1] start processing
14:57:54 - cmdstanpy - INFO - Chain [1] done processing
14:57:57 - cmdstanpy - INFO - Chain [1] start processing
14:57:58 - cmdstanpy - INFO - Chain [1] done processing
14:58:02 - cmdstanpy - INFO - Chain [1] start processing
14:58:04 - cmdstanpy - INFO - Chain [1] done processing
14:58:06 - cmdstanpy - INFO - Chain [1] start processing
14:58:09 - cmdstanpy - INFO - Chain [1] done processing

{100356.0: 9.485205219021742,
 100619.0: 0.16719939903013792,
 109269.0: 3.751881491669695,
 101744.0: -0.46124801409908045,
 100800.0: 49.028932549883365,
 135599.0: 5.543791649947494,
 101952.0: 3.8850859413490646,
 100177.0: 10.917967076529212,
 101588.0: 2.615274128142575,
 100940.0: 5.182465701763661}

In [39]:
def get_top_5_scores(scores_df):
    # Sort the dictionary by values in descending order
    sorted_scores = sorted(scores_df.items(), key=lambda x: x[1], reverse=True)
    top_5_key_value_pair={}
    
    for i, (key, value) in enumerate(sorted_scores[:5]):
        top_5_key_value_pair[key]=value
    return top_5_key_value_pair

In [40]:
top_scheme_codes=get_top_5_scores(scores_df)

In [41]:
print(top_scheme_codes)

{100800.0: 49.028932549883365, 100177.0: 10.917967076529212, 100356.0: 9.485205219021742, 135599.0: 5.543791649947494, 100940.0: 5.182465701763661}

In [42]:
for key in top_scheme_codes:
    scheme_code = int(key)
    if scheme_code_to_risk[scheme_code] == 0:
       risk = 1
    elif scheme_code_to_risk[scheme_code] == 0.1:
       risk = 2
    elif scheme_code_to_risk[scheme_code] == 0.2:
       risk = 3
    elif scheme_code_to_risk[scheme_code] == 0.3:
       risk = 4
    elif scheme_code_to_risk[scheme_code] == 0.4:
       risk = 5
    else:
       risk = 6
    print("Scheme Name:", scheme_code_to_names[scheme_code], ",", "Risk:", risk)

Scheme Name: UTI-Treasury Advantage Fund , Risk: 2
Scheme Name: Quant Liquid Plan – Direct Growth , Risk: 2
Scheme Name: ICICI Pru Corporate Bond Fund , Risk: 2
Scheme Name: PGIM India Low Duration Fund , Risk: 2
Scheme Name: DSP Low Duration Fund , Risk: 2